#!/bin/sh

. /lib/functions.sh

#todo - generate password based on serial, disable root-login by ssh

CryptPassword=$(cryptpw "DEVICE_PASSWORD")
sed -i "s,^root:[^:]\+:,root:$CryptPassword:," /etc/shadow
sed -i "s,^admin:[^:]\+:,admin:$CryptPassword:," /etc/shadow
sed -i "s,^user:[^:]\+:,user:$CryptPassword:," /etc/shadow
sed -i "s,^operator:[^:]\+:,operator:$CryptPassword:," /etc/shadow
