name: release

on:
  push:
    branches:
      - main
    paths:
      - 'release.version'

jobs:
  build_release:
    #if: startsWith(github.ref, 'refs/tags/v')
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version
        run: echo "::set-output name=version::$(cat ./release.version)"
        id: version         
      - name: build artifacts
        env:
          DEVICE_PASSWORD: ${{ secrets.DEVICE_PASSWORD }} 
          CWMP_CPE_PASSWORD: ${{ secrets.CWMP_CPE_PASSWORD }} 
          CWMP_ACS_PASSWORD: ${{ secrets.CWMP_ACS_PASSWORD }} 
        run: make opdefaults_build
      - name: push tag with version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}         
      - name: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true 
          artifacts: "witcom-opdefaults-${{ steps.version.outputs.version }}.tar.gz"
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}        